create table booked_tickets (booked_ticket_id bigint not null, email varchar(255), owner_name varchar(255), owner_surname varchar(255), booking_id bigint not null, ticket_id bigint not null, primary key (booked_ticket_id));
create table bookings (booking_id bigint not null, booking_date_time timestamp(6) not null, user_id bigint not null, primary key (booking_id));
create table categories (id bigint not null, category_name varchar(255) not null, primary key (id));
create table events (id bigint not null, booking_deadline timestamp(6) not null, event_date_time timestamp(6) not null, event_image varchar(255), event_name varchar(255), event_description TEXT, category_id bigint not null, performer_id bigint, venue_id bigint not null, primary key (id));
create table performers (id bigint not null, performer_description TEXT, performer_name varchar(255), primary key (id));
create table tickets (ticket_type_id bigint not null, amount integer, available_slots integer, price integer, zone_name varchar(255), event_id bigint not null, primary key (ticket_type_id));
create table user_role (user_id bigint not null, roles varchar(255) check (roles in ('ROLE_CUSTOMER','ROLE_ADMIN','ROLE_MANAGER')));
create table users (id bigint not null, email varchar(255) not null, firstname varchar(255), lastname varchar(255), password varchar(255) not null, phone varchar(255), primary key (id));
create table venues (id bigint not null, address varchar(255) not null, capacity integer, city varchar(255) not null, country varchar(255) not null, venue_name varchar(255) not null, zone_amount integer, primary key (id));
create sequence booked_tickets_seq start with 1 increment by 50;
create sequence bookings_seq start with 1 increment by 50;
create sequence categories_id_seq start with 1 increment by 1;
create sequence events_id_seq start with 1 increment by 1;
create sequence performers_id_seq start with 1 increment by 1;
create sequence tickets_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create sequence venues_id_seq start with 1 increment by 1;
alter table if exists booked_tickets add constraint FKrv68f9o0hjap0dcq1v7gjxyrn foreign key (booking_id) references bookings;
alter table if exists booked_tickets add constraint FKrqsfkjyc4geeobmjy1gdopy8i foreign key (ticket_id) references tickets;
alter table if exists bookings add constraint FKeyog2oic85xg7hsu2je2lx3s6 foreign key (user_id) references users;
alter table if exists events add constraint FKo6mla8j1p5bokt4dxrlmgwc28 foreign key (category_id) references categories;
alter table if exists events add constraint FKf10ja0xfmfgxnb83sa3ly34td foreign key (performer_id) references performers;
alter table if exists events add constraint FKqdxygdernwwt74hdvix9u5nr3 foreign key (venue_id) references venues;
alter table if exists tickets add constraint FK3utafe14rupaypjocldjaj4ol foreign key (event_id) references events;
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;